version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=h2
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:testdb
      - SPRING_DATASOURCE_DRIVERCLASSNAME=org.h2.Driver
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.H2Dialect
      - SPRING_H2_CONSOLE_ENABLED=true
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - h2-console
    networks:
      - app-network

  h2-console:
    image: oscarfonts/h2
    ports:
      - "8082:81"
    environment:
      - H2_OPTIONS=-ifNotExists
    volumes:
      - h2-data:/h2-data
    networks:
      - app-network

volumes:
  h2-data:

networks:
  app-network:
    driver: bridge 