version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: demo_postgres
    environment:
      POSTGRES_DB: demo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - demo-network

  memcached:
    image: memcached:1.6-alpine
    container_name: demo_memcached
    ports:
      - "11211:11211"
    command: memcached -m 128
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "11211"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - demo-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: demo_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - demo-network

volumes:
  postgres_data:

networks:
  demo-network:
    driver: bridge 